sonar.projectKey=huawei-health-ai-backend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.module.ts,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
